services:
  app:
    build:
      dockerfile: Dockerfile
    command: bash -c "ng serve --host 0.0.0.0 & npm run start"
    ports:
      - "3000:3000"  # Expressアプリケーション用
      - "4200:4200"  # Angularアプリケーション用
    volumes:
      - .:/app
    working_dir: /app/frontend
